"""Add management_status field to Case model

Revision ID: 9064f0eb7540
Revises: 
Create Date: 2025-12-29 22:23:47.977177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9064f0eb7540'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('management_status', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_cases_management_status'), 'cases', ['management_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cases_management_status'), table_name='cases')
    op.drop_column('cases', 'management_status')
    # ### end Alembic commands ###

